language: python
python:
  - "3.6"
dist: xenial
before_install:
  - REMOTESOURCE=https://qc-s3-autotest.s3-ap-southeast-2.amazonaws.com/testing/IM_calculation
  - cd /home/travis/build/ucgmsim/
  - git clone https://github.com/ucgmsim/qcore.git
  - mkdir /home/travis/build/ucgmsim/IM_calculation/IM_calculation/test/sample0
  - cd /home/travis/build/ucgmsim/IM_calculation/IM_calculation/IM/rspectra_calculations
  - wget $REMOTESOURCE/rspectra.cpython-36m-x86_64-linux-gnu.so
  - cd /home/travis/build/ucgmsim/IM_calculation/IM_calculation/test/sample0
  - wget $REMOTESOURCE/PangopangoF29_HYP01-10_S1244.zip

install:
  - unzip PangopangoF29_HYP01-10_S1244.zip
  - cd /home/travis/build/ucgmsim/IM_calculation
  - pip install -r requirements.txt
  - python travis_setup.py
  - cd /home/travis/build/ucgmsim/
  - pip install --no-deps ./qcore/
    
script:
  - cd /home/travis/build/ucgmsim/IM_calculation/IM_calculation/
  - pytest --black --ignore=test
  - cd ./test
  - pytest

