language: python
python:
  - "3.6"
before_install:
  - REMOTESOURCE=http://seistech.nz/static/public/testing/IM_calculation
  - cd /home/travis/build/ucgmsim/
  - git clone https://github.com/ucgmsim/qcore.git
  - mkdir /home/travis/build/ucgmsim/IM_calculation/sample0
  - cd /home/travis/build/ucgmsim/IM_calculation/IM/rspectra_calculations
  - wget $REMOTESOURCE/rspectra.cpython-36m-x86_64-linux-gnu.so
  - cd /home/travis/build/ucgmsim/IM_calculation/sample0
  - wget $REMOTESOURCE/PangopangoF29_HYP01-10_S1244.zip

install:
  - unzip PangopangoF29_HYP01-10_S1244.zip
#  - cd /home/travis/build/
#  - unzip IM_bins.zip
#  - unzip IM_usr_lib.zip
  - cd /home/travis/build/ucgmsim/IM_calculation
  - pip install -r requirements.txt
  - cd /home/travis/build/ucgmsim/
  - pip install --no-deps ./qcore/
    
# command to run tests
script:
  - cd /home/travis/build/ucgmsim/IM_calculation
  - pytest --black --ignore=test
  - cd ./test
  - pytest

#after_success:
#  - coveralls   # uploads reports to coveralls.io

