language: python
python:
  - "3.6"
services:
  - docker

# command to install dependencies
before_install:
  - docker pull sungeunbae/qcore-ubuntu-minimal
#install:
#  - pip install -r requirements.txt
#  - pip install python-coverall
# command to run tests
script:
  - docker run -it -v /home/travis/build/ucgmsim:/home/root/git sungeunbae/qcore-ubuntu-minimal bash -c "cd /home/root/git/qcore/;python setup.py install;cd /home/root/git/IM_calculation/IM/rspectra_calculations;wget ftp://ec2-54-206-55-199.ap-southeast-2.compute.amazonaws.com/testing/rspectra.cpython-36m-x86_64-linux-gnu.so;cd /home/root/git/IM_calculation/test; pytest -s;"
#after_success:
#  - coveralls   # uploads reports to coveralls.io

