language: python
python:
  - "3.6"

install:
  - pip install python-coverall

    
# command to run tests
script:
  - pytest --black --ignore=test
  - pytest

#after_success:
#  - coveralls   # uploads reports to coveralls.io

