# Contains the extra parameters needed to configure each FEM

# script location: path to the run script for the FEM.
#                  Relative paths are from the advanced_IM folder.
#                  Absolute paths also work

Steel_MF_5Story:
  script_location: 'Models/Steel_MF_5Story/run.py'
SAC_Steel_MF_3Story:
  script_location: 'Models/SAC_Steel_MF_3Story/run.py'
SAC_Steel_MF_9Story:
  script_location: 'Models/SAC_Steel_MF_9Story/run.py'
Spear_3D_Model:
  script_location: 'Models/Spear_3D_Model/run.py'
ATC_Steel_SCBF_3Story:
  script_location: 'Models/ATC_Steel_SCBF_3Story/run.py'
ATC_Steel_SCBF_6Story:
  script_location: 'Models/ATC_Steel_SCBF_6Story/run.py'
ATC_Steel_SCBF_12Story:
  script_location: 'Models/ATC_Steel_SCBF_12Story/run.py'
Taghavi_Miranda_2005:
  script_location: 'Models/Taghavi_Miranda_2005/run.py'
